#!/bin/bash

if [[ -z "$SNABB" ]]; then
    echo "Please set SNABB to the location of the snabb repository"
    exit 1
fi
if [[ -z "$SPIKE" ]]; then
    echo "Please set SPIKE to the location of the spike repository"
    exit 1
fi

export LIBSPIKE="$SPIKE/libspike.so"
SNABB="$SNABB/src/snabb"

if [[ -n "$DEBUG" ]]; then
    COMMAND="gdb --args $SNABB"
else
    COMMAND="$SNABB"
fi

$COMMAND snsh -P "$SPIKE/forward/?.lua" "$SPIKE/forward/spike.lua" "$@"
