#!/bin/bash

if [[ -z "$SNABB" ]]; then
    echo "Please set SNABB to the location of the snabb repository"
    exit 1
fi
if [[ -z "$SPIKE" ]]; then
    echo "Please set SPIKE to the location of the spike repository"
    exit 1
fi

$SNABB/src/snabb snsh -P $SPIKE/forward/grewrap.lua $SPIKE/forward/spike.lua
